package com.eight87.tonearmboy.ui.nav

import androidx.navigation3.runtime.NavKey
import kotlinx.serialization.Serializable

/**
 * Navigation 3 destinations for tonearmboy.
 *
 * The app has **one** root destination — [LibraryRoot] — which renders
 * the library top-tabs (Songs / Albums / Artists / Genres / Playlists)
 * under a `TopAppBar`. Everything else is pushed onto the same single
 * stack: search, settings root + sub-pages, the now-playing surface,
 * and per-playlist detail. There is no bottom navigation; the
 * mini-player is the only persistent bottom UI element.
 *
 * All keys are `@Serializable` because [androidx.navigation3.runtime.rememberNavBackStack]
 * round-trips the stack through `SavedStateHandle` for config-change /
 * process-death survival, which requires kotlinx.serialization support.
 */
sealed interface Destination : NavKey

/** Root: library top-tabs under the `tonearmboy` top app bar. */
@Serializable
data object LibraryRoot : Destination

/** Search surface (entered from the top-bar search icon). */
@Serializable
data object Search : Destination

/** Full-screen now-playing surface (also reachable from the mini-player). */
@Serializable
data object NowPlaying : Destination

/** Detail screen for a single user playlist. */
@Serializable
data class PlaylistDetail(val playlistId: Long) : Destination

/**
 * D.27.3 — multi-select-only library Songs view used by the playlist
 * detail "Add tracks" / `+` flow. Pre-checks tracks already in the
 * playlist so the picker doubles as "remove from playlist by
 * unchecking a row".
 */
@Serializable
data class PlaylistTrackPicker(val playlistId: Long) : Destination

/**
 * D.15.1 — detail screen for a single album. The album is identified by
 * its (name, albumArtist|artist) pair rather than the rollup id, since
 * the rollup id can shift between rescans (Room autogenerated key).
 */
@Serializable
data class AlbumDetail(val name: String, val albumArtist: String?) : Destination

/** D.15.2 — detail screen for a single artist (keyed by name). */
@Serializable
data class ArtistDetail(val name: String) : Destination

/** D.15.3 — detail screen for a single genre (keyed by name). */
@Serializable
data class GenreDetail(val name: String) : Destination

// --- Settings -------------------------------------------------------------

/** Settings root with the eight Auxio-style entries. */
@Serializable
data object SettingsRootDest : Destination

@Serializable
data object SettingsLookAndFeel : Destination

@Serializable
data object SettingsPersonalize : Destination

@Serializable
data object SettingsContent : Destination

@Serializable
data object SettingsAudio : Destination

/**
 * D.9d.1 — Music sources sub-page (Settings > Library > Music sources).
 * Hosts the SAF directory picker entry-point and the list of currently
 * configured tree URIs.
 */
@Serializable
data object SettingsMusicSources : Destination

/** Full-screen global settings search overlay (entered from the Settings root). */
@Serializable
data object SettingsSearch : Destination

/**
 * D.16.4 — About sub-page. Reachable from the Settings root Library
 * card. Shows app name + version + build SHA + build date, GitHub link,
 * MIT license note, and a credits list. Also hosts the build-version
 * easter-egg tap counter (D.16.5).
 */
@Serializable
data object SettingsAbout : Destination

/**
 * Open-source licenses sub-page. Reachable from the About screen.
 * Renders the inventory generated by the Licensee Gradle plugin
 * at build time (`assets/licenses/artifacts.json`).
 */
@Serializable
data object SettingsLicenses : Destination

/**
 * D.30.3 — full-screen editor for a custom library tab. `tabId == null`
 * means "create new"; a non-null id loads the matching
 * [com.eight87.tonearmboy.data.db.CustomTabEntity] for editing. Replaces
 * the pre-D.30.3 `ModalBottomSheet`-based `CustomTabEditorSheet` so
 * the form (name + content type + filter conditions) gets a proper
 * top-app-bar with back / save and full vertical real estate.
 */
@Serializable
data class CustomTabEditor(val tabId: Long? = null) : Destination
