package com.eight87.tonearmboy.data.db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Fts4
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Cached representation of a MediaStore audio row.
 *
 * Primary key is the MediaStore `_ID`, which lets us delete + upsert
 * cheaply during incremental rescans without keeping a side-mapping.
 */
@Entity(
  tableName = "tracks",
  indices = [
    Index("title"),
    Index("artist"),
    Index("album"),
    Index("albumArtist"),
    Index("genre"),
  ],
)
data class TrackEntity(
  @PrimaryKey val id: Long,
  val title: String,
  val artist: String?,
  val album: String?,
  val albumArtist: String?,
  val durationMs: Long,
  val trackNumber: Int?,
  val year: Int?,
  val genre: String?,
  /** Absolute filesystem path (`MediaStore.Audio.Media.DATA`). */
  val data: String,
  val dateAddedSeconds: Long,
  /**
   * D.9b.1 — track-level ReplayGain in dB (parsed from
   * `REPLAYGAIN_TRACK_GAIN` Vorbis-comment / ID3v2 TXXX). Negative
   * values are common (the standard reduces, never amplifies).
   * Null when the tag is missing or unparseable.
   */
  val replayGainTrackDb: Float? = null,
  /** D.9b.1 — track-level peak (linear, 0.0..1.0+). Null when missing. */
  val replayGainTrackPeak: Float? = null,
  /**
   * D.9b.3 — MediaStore album id (`MediaStore.Audio.Media.ALBUM_ID`).
   * Used to resolve album-art via the legacy
   * `content://media/external/audio/albumart/<id>` provider, which is
   * keyed by this id rather than our autogenerated rollup id.
   */
  val mediaStoreAlbumId: Long? = null,
)

/**
 * FTS4 mirror of [TrackEntity]. Used by [com.eight87.tonearmboy.data.LibraryRepository.search].
 *
 * Declared as a content-entity FTS table — Room keeps the FTS row in
 * sync with the contentEntity by mirroring inserts and deletes
 * (`rowid` is matched to the content table's primary key column).
 */
@Fts4(contentEntity = TrackEntity::class)
@Entity(tableName = "tracks_fts")
data class TrackFts(
  val title: String,
  val artist: String?,
  val album: String?,
)

/**
 * Albums are derived (album_name + albumArtist), but cached as a row to
 * keep the join cheap and to give the UI a stable id for navigation.
 */
@Entity(
  tableName = "albums",
  indices = [Index(value = ["name", "artist"], unique = true)],
)
data class AlbumEntity(
  @PrimaryKey(autoGenerate = true) val id: Long = 0,
  val name: String,
  val artist: String?,
  val year: Int?,
  /**
   * D.9b.1 — album-level ReplayGain in dB. The album-tagged value is
   * the same on every track of an album; deriveAlbums picks the first
   * non-null value seen across the album's tracks.
   */
  val replayGainAlbumDb: Float? = null,
  /** D.9b.1 — album-level peak (linear). Null when missing. */
  val replayGainAlbumPeak: Float? = null,
  /**
   * D.9b.3 — MediaStore album id used for the album-art content URI.
   * Folded in from the per-track `ALBUM_ID` during scan; the standard
   * holds that all tracks of an album share the same id, so we keep
   * the first non-null value seen.
   */
  val mediaStoreAlbumId: Long? = null,
)

@Entity(
  tableName = "artists",
  indices = [Index(value = ["name"], unique = true)],
)
data class ArtistEntity(
  @PrimaryKey(autoGenerate = true) val id: Long = 0,
  val name: String,
)

@Entity(
  tableName = "genres",
  indices = [Index(value = ["name"], unique = true)],
)
data class GenreEntity(
  @PrimaryKey(autoGenerate = true) val id: Long = 0,
  val name: String,
)

@Entity(
  tableName = "playlists",
  indices = [Index(value = ["name"], unique = true)],
)
data class PlaylistEntity(
  @PrimaryKey(autoGenerate = true) val id: Long = 0,
  val name: String,
  val createdAtSeconds: Long,
  /**
   * D.27.6 — optional cover image URI for the playlist tile. Stored as
   * an opaque string so we can hold either a `content://` SAF URI
   * (user-picked image, persisted via `takePersistableUriPermission`)
   * or a `mediastore://` form pointing at a track's album-art id. Null
   * means: fall back to the first track's album art, then the
   * letter-avatar default. The chooser sheet writes this column via
   * [com.eight87.tonearmboy.data.LibraryRepository.setPlaylistCoverUri].
   */
  val coverUri: String? = null,
)

/**
 * Join table between playlists and tracks. `position` is 0-indexed and
 * used by `reorderPlaylist`. Cascading delete on the playlist side; on
 * the track side we rely on application-level cleanup (the repository
 * removes the join row when a track disappears from MediaStore).
 */
@Entity(
  tableName = "playlist_tracks",
  primaryKeys = ["playlistId", "position"],
  indices = [
    Index("trackId"),
    Index(value = ["playlistId", "trackId"]),
  ],
  foreignKeys = [
    ForeignKey(
      entity = PlaylistEntity::class,
      parentColumns = ["id"],
      childColumns = ["playlistId"],
      onDelete = ForeignKey.CASCADE,
    ),
    ForeignKey(
      entity = TrackEntity::class,
      parentColumns = ["id"],
      childColumns = ["trackId"],
      onDelete = ForeignKey.CASCADE,
    ),
  ],
)
data class PlaylistTrackEntity(
  val playlistId: Long,
  val trackId: Long,
  @ColumnInfo(name = "position") val position: Int,
)

/**
 * D.18.1 — A user-defined library tab keyed on a content kind plus a
 * filter expression. The criteria are stored as JSON encoded by
 * [com.eight87.tonearmboy.data.FilterCriteria]; we keep them as a single
 * column rather than splitting per-predicate so the schema doesn't
 * fan out every time a new predicate is added.
 *
 * `position` is the user's ordering relative to other custom tabs;
 * built-in tabs have their own ordering in `SettingsRepository.libraryTabs`
 * and the rail concatenates the two lists at render time.
 */
@Entity(tableName = "custom_tabs")
data class CustomTabEntity(
  @PrimaryKey(autoGenerate = true) val id: Long = 0,
  val name: String,
  val position: Int,
  val contentType: CustomTabContentType,
  val criteriaJson: String,
)

/** D.18.1 — what a custom tab renders. */
enum class CustomTabContentType { SONGS, ALBUMS, ARTISTS, GENRES }
