package com.eight87.tonearmboy.data.db

import androidx.room.Entity
import androidx.room.Fts4
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Cached representation of a MediaStore audio row.
 *
 * Primary key is the MediaStore `_ID`, which lets us delete + upsert
 * cheaply during incremental rescans without keeping a side-mapping.
 */
@Entity(
  tableName = "tracks",
  indices = [
    Index("title"),
    Index("artist"),
    Index("album"),
    Index("albumArtist"),
    Index("genre"),
  ],
)
data class TrackEntity(
  @PrimaryKey val id: Long,
  val title: String,
  val artist: String?,
  val album: String?,
  val albumArtist: String?,
  val durationMs: Long,
  val trackNumber: Int?,
  val year: Int?,
  val genre: String?,
  /** Absolute filesystem path (`MediaStore.Audio.Media.DATA`). */
  val data: String,
  val dateAddedSeconds: Long,
  /**
   * D.9b.1 — track-level ReplayGain in dB (parsed from
   * `REPLAYGAIN_TRACK_GAIN` Vorbis-comment / ID3v2 TXXX). Negative
   * values are common (the standard reduces, never amplifies).
   * Null when the tag is missing or unparseable.
   */
  val replayGainTrackDb: Float? = null,
  /** D.9b.1 — track-level peak (linear, 0.0..1.0+). Null when missing. */
  val replayGainTrackPeak: Float? = null,
  /**
   * D.9b.3 — MediaStore album id (`MediaStore.Audio.Media.ALBUM_ID`).
   * Used to resolve album-art via the legacy
   * `content://media/external/audio/albumart/<id>` provider, which is
   * keyed by this id rather than our autogenerated rollup id.
   */
  val mediaStoreAlbumId: Long? = null,
)

/**
 * FTS4 mirror of [TrackEntity]. Used by [com.eight87.tonearmboy.data.LibraryRepository.search].
 *
 * Declared as a content-entity FTS table — Room keeps the FTS row in
 * sync with the contentEntity by mirroring inserts and deletes
 * (`rowid` is matched to the content table's primary key column).
 */
@Fts4(contentEntity = TrackEntity::class)
@Entity(tableName = "tracks_fts")
data class TrackFts(
  val title: String,
  val artist: String?,
  val album: String?,
)
